# Generated by Django 4.1.3 on 2023-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='posts/')),
                ('slug', models.SlugField(max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created']},
        ),
    ]
