# Generated by Django 4.1.3 on 2023-06-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
