# Generated by Django 4.1.3 on 2023-06-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
