# Generated by Django 4.1.3 on 2023-06-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='posts/')),
                ('slug', models.SlugField(max_length=256)),
            ],
        ),
    ]
